stages:
- test

Test_PerlCheck:
  tags:
  - Perl
  stage: test
  script:
  - perlcheck $CI_PROJECT_DIR

Test_PerlCritic:
  tags:
  - PerlCritic
  stage: test
  script:
  - perlcritic --quiet --statistics -4 $CI_PROJECT_DIR
  allow_failure: true